# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'PantryPal-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya', '~> 11.0'
  pod 'RealmSwift', '3.11.0'
  pod 'Kingfisher'
  pod 'Marshal'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # Pods for PantryPal-iOS

  target 'PantryPal-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PantryPal-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
